version: '3.3'
services:
  _build:
    # as dockerfile also provide, will create image ddd-todo-list
    image: ddd-todo-list
    command: ['echo', 'build completed']
    build:
      context: .
      dockerfile: Dockerfile

  shell:
    image: ddd-todo-list
    container_name: shell
    depends_on:
      - _build
    command: tail -f /dev/null
    volumes:
      - .:/home/app
      - ./node_modules:/home/app/node_modules

  server:
    depends_on:
      - _build
    container_name: 'server'
    command: ['yarn', 'start:dev']
    image: ddd-todo-list
    build:
      context: .
      target: dev
    ports:
      - 4000:4000
    volumes:
      - .:/home/app/
      - ./node_modules:/home/app/node_modules
    environment:
      - PORT=4000
      - NODE_ENV=development

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
