# name of workflow
name: 'ddd-todo-list ci/cd pipeline'

# triggers for workflow to run
on:
  push:
    branches:
      - prod
  # pull_request:
  #   branches:
  #     - prod

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install global Dependencies in workspace
        run: |
          yarn policies set-version 3.5.1
          yarn install --frozen-lockfile

      - name: Run Linting
        run: yarn lint

      - name: Run formatting
        run: yarn format

      - name: Run client tests
        run: yarn test:client

      - name: Run server tests
        run: yarn test:server
